server:
  port: 80
swagger:
  show: true

#配置数据源
spring:
  datasource:
    #表示任何类型数据库都进行数据库初始化,
    initialization-mode: always
    #启动时需要初始化的建表语句
    schema: classpath:sql/schema.sql
    #初始化的数据
    data: classpath:sql/data.sql
    driver-class-name: com.mysql.cj.jdbc.Driver
    #创建数据库编码为utf8mb4
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=UTC
    username: root
    password: root

#配置mybatis
mybatis:
  ## mybatis的路径，我们放到resources下的mapper文件夹下面
  mapper-locations: classpath:mapper/*.xml
  ## 默认别名就是实体类名，或者类名首字母小写
  type-aliases-package: com.example.entity

redis:
  # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
  database: 0
  # redis服务器地址（默认为loaclhost）
  host: 127.0.0.1
  # redis端口（默认为6379）
  port: 6379
  # redis连接超时时间（单位毫秒）
  timeout: 5000ms
  # redis连接池配置
  pool:
    # 最大可用连接数（默认为8，负数表示无限）
    max-active: 8
    # 最大空闲连接数（默认为8，负数表示无限）
    max-idle: 8
    # 最小空闲连接数（默认为0，该值只有为正数才有用）
    min-idle: 0
    # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
    max-wait: -1
